server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Esta línea es CLAVE para las Single Page Applications (SPA) como React (con React Router)
        # Si la ruta no es un archivo ni un directorio, devuelve el index.html
        try_files $uri $uri/ /index.html;

        # Content Security Policy
        add_header Content-Security-Policy "
            default-src 'self';
            script-src 'self' 'unsafe-inline';
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
            font-src 'self' https://fonts.gstatic.com;
            img-src 'self' data:;
            connect-src 'self' /api;
            frame-ancestors 'none';
        " always;
    }

    # Proxy para el backend
    location /api/ {
        proxy_pass http://sgifiis-backend-api-dev:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Opcional: Configuraciones para optimizar caché de archivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
