server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Esta línea es CLAVE para las Single Page Applications (SPA) como React (con React Router)
        # Si la ruta no es un archivo ni un directorio, devuelve el index.html
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuraciones para optimizar caché de archivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
