import type {
  AnalyticsData,
  DashboardData,
  FinancingData,
  PublicationsData,
  RankingData,
  ReportsData,
  ResearchersData,
} from '../types/dashboard.types';

export async function getDashboardData(): Promise<DashboardData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'calls',
        title: 'Convocatorias Activas',
        value: '03',
        detail: '+1 nueva',
        icon: '▢',
        tone: 'primary',
      },
      {
        id: 'projects',
        title: 'Proyectos en Ejecución',
        value: '18',
        detail: 'seguimiento activo',
        icon: '↧',
        tone: 'primary',
      },
      {
        id: 'pending',
        title: 'Trámites por Resolver',
        value: '07',
        detail: 'URGENTE',
        icon: '!',
        tone: 'danger',
      },
      {
        id: 'thesis',
        title: 'Planes de Tesis Registrados',
        value: '12',
        detail: 'procesos vigentes',
        icon: '◇',
        tone: 'primary',
      },
    ],
    groups: [
      {
        id: 'ginsoft',
        name: 'GINSOFT',
        description: 'Grupo de Ingeniería de Software',
        totalProjects: 15,
        postulated: 35,
        approved: 25,
        execution: 30,
        observed: 10,
      },
      {
        id: 'resegt',
        name: 'RESEGTI',
        description: 'Seguridad y Gestión TI',
        totalProjects: 12,
        postulated: 25,
        approved: 30,
        execution: 30,
        observed: 15,
      },
      {
        id: 'datasci',
        name: 'DATASCI',
        description: 'Ciencia de Datos e IA',
        totalProjects: 18,
        postulated: 30,
        approved: 30,
        execution: 30,
        observed: 10,
      },
    ],
    approvalSteps: [
      {
        id: 'postulado',
        title: 'Postulado',
        description: 'Expedientes recibidos',
        value: '10',
        tone: 'active',
      },
      {
        id: 'coordinador',
        title: 'Pend. Coordinador',
        description: 'Evaluación técnica inicial',
        value: '5',
        tone: 'normal',
      },
      {
        id: 'director',
        title: 'Pend. Director',
        description: 'Revisión de viabilidad',
        value: '3',
        tone: 'normal',
      },
      {
        id: 'decano',
        title: 'Pend. Decano',
        description: 'Firma de resolución',
        value: '2',
        tone: 'warning',
      },
      {
        id: 'aprobado',
        title: 'Aprobado con Resolución',
        description: 'Ciclo completado',
        value: '✓',
        tone: 'success',
      },
    ],
    pendingProcedures: [
      {
        id: 'p-1',
        code: 'FIIS-2026-0089',
        applicant: 'Dr. Ricardo Palma',
        type: 'postulacion',
        typeLabel: 'Postulación de Proyecto',
        title: 'Optimización de Redes Neuronales en IoT',
        category: 'Fondo Concursable 2026',
        status: 'PENDIENTE_DECANATO',
        time: 'Hace 3 días',
        priority: 'alta',
      },
      {
        id: 'p-2',
        code: 'FIIS-2026-0104',
        applicant: 'Dra. Elena Vizcarra',
        type: 'informe',
        typeLabel: 'Informe de Avance',
        title: 'Ciberseguridad en Infraestructuras Críticas',
        category: 'Investigación Docente',
        status: 'EN_REVISIÓN',
        time: 'Hace 1 día',
        priority: 'alta',
      },
      {
        id: 'p-3',
        code: 'FIIS-2026-0112',
        applicant: 'Mg. Carlos Aranda',
        type: 'tesis',
        typeLabel: 'Plan de Tesis',
        title: 'Gestión de Residuos Electrónicos con Blockchain',
        category: 'Proyecto Multidisciplinario',
        status: 'PENDIENTE_COORDINADOR',
        time: 'Hace 5 días',
        priority: 'media',
      },
    ],
  };
}

export async function getAnalyticsData(): Promise<AnalyticsData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'approval-rate',
        title: 'Tasa de aprobación',
        value: '68%',
        detail: '+8% frente al periodo anterior',
        tone: 'primary',
      },
      {
        id: 'avg-resolution',
        title: 'Tiempo promedio de resolución',
        value: '12 días',
        detail: 'Promedio institucional',
        tone: 'primary',
      },
      {
        id: 'observed',
        title: 'Proyectos observados',
        value: '06',
        detail: 'Requieren levantamiento de observaciones',
        tone: 'danger',
      },
      {
        id: 'active-groups',
        title: 'Grupos activos',
        value: '08',
        detail: 'Con producción investigativa registrada',
        tone: 'primary',
      },
    ],
    projectStatus: [
      {
        id: 'postulated',
        label: 'Postulados',
        value: 10,
        detail: 'proyectos',
        percentage: 25,
      },
      {
        id: 'approved',
        label: 'Aprobados',
        value: 14,
        detail: 'proyectos',
        percentage: 35,
      },
      {
        id: 'execution',
        label: 'En ejecución',
        value: 12,
        detail: 'proyectos',
        percentage: 30,
      },
      {
        id: 'observed',
        label: 'Observados',
        value: 4,
        detail: 'proyectos',
        percentage: 10,
      },
    ],
    groupPerformance: [
      {
        id: 'ginsoft',
        label: 'GINSOFT',
        value: 15,
        detail: 'registros',
        percentage: 83,
      },
      {
        id: 'datasci',
        label: 'DATASCI',
        value: 18,
        detail: 'registros',
        percentage: 78,
      },
      {
        id: 'resegt',
        label: 'RESEGTI',
        value: 12,
        detail: 'registros',
        percentage: 66,
      },
      {
        id: 'sistemas',
        label: 'SISTEMAS',
        value: 9,
        detail: 'registros',
        percentage: 52,
      },
    ],
    monthlyTrend: [
      { month: 'Ene', projects: 6, procedures: 3, evaluations: 4 },
      { month: 'Feb', projects: 8, procedures: 4, evaluations: 5 },
      { month: 'Mar', projects: 11, procedures: 5, evaluations: 7 },
      { month: 'Abr', projects: 9, procedures: 6, evaluations: 6 },
      { month: 'May', projects: 13, procedures: 7, evaluations: 9 },
      { month: 'Jun', projects: 15, procedures: 8, evaluations: 10 },
    ],
    insights: [
      'Los proyectos en ejecución concentran la mayor actividad institucional del periodo.',
      'Las observaciones se presentan principalmente antes de la revisión de dirección.',
      'Los grupos GINSOFT y DATASCI registran mayor producción investigativa.',
      'La cantidad de trámites mantiene crecimiento sostenido desde marzo.',
    ],
  };
}

export async function getReportsData(): Promise<ReportsData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'generated',
        title: 'Reportes generados',
        value: '24',
        detail: 'durante el periodo actual',
        tone: 'primary',
      },
      {
        id: 'pending',
        title: 'Reportes pendientes',
        value: '04',
        detail: 'en proceso de consolidación',
        tone: 'danger',
      },
      {
        id: 'exports',
        title: 'Exportaciones',
        value: '18',
        detail: 'PDF y Excel descargados',
        tone: 'primary',
      },
      {
        id: 'validated',
        title: 'Reportes validados',
        value: '12',
        detail: 'aprobados por gestión académica',
        tone: 'primary',
      },
    ],
    reports: [
      {
        id: 'rep-1',
        title: 'Reporte ejecutivo de proyectos',
        description:
          'Resumen de proyectos postulados, aprobados, observados y en ejecución.',
        format: 'PDF',
        status: 'disponible',
        updatedAt: 'Actualizado hoy',
      },
      {
        id: 'rep-2',
        title: 'Reporte de evaluaciones institucionales',
        description:
          'Detalle de evaluaciones realizadas, resultados y observaciones registradas.',
        format: 'Excel',
        status: 'disponible',
        updatedAt: 'Actualizado ayer',
      },
      {
        id: 'rep-3',
        title: 'Reporte de trámites pendientes',
        description:
          'Listado consolidado de expedientes pendientes de resolución institucional.',
        format: 'PDF',
        status: 'disponible',
        updatedAt: 'Hace 2 días',
      },
      {
        id: 'rep-4',
        title: 'Reporte de grupos de investigación',
        description:
          'Indicadores de actividad, producción y participación por grupo.',
        format: 'Excel',
        status: 'pendiente',
        updatedAt: 'En consolidación',
      },
    ],
    summary:
      'Durante el periodo actual se consolidaron reportes asociados a proyectos de investigación, evaluaciones académicas y trámites pendientes. La mayor demanda se concentra en reportes ejecutivos y reportes de seguimiento por grupo de investigación.',
  };
}

export async function getPublicationsData(): Promise<PublicationsData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'registered',
        title: 'Publicaciones registradas',
        value: '58',
        detail: '+6 frente al periodo anterior',
        tone: 'primary',
      },
      {
        id: 'review',
        title: 'En revisión editorial',
        value: '14',
        detail: 'pendientes de seguimiento',
        tone: 'danger',
      },
      {
        id: 'indexed',
        title: 'Publicaciones indexadas',
        value: '32',
        detail: 'Scopus, IEEE y SciELO',
        tone: 'primary',
      },
      {
        id: 'groups',
        title: 'Grupos con producción',
        value: '08',
        detail: 'con artículos registrados',
        tone: 'primary',
      },
    ],
    channels: [
      {
        id: 'scopus',
        label: 'Scopus',
        value: 18,
        percentage: 56,
      },
      {
        id: 'ieee',
        label: 'IEEE',
        value: 8,
        percentage: 25,
      },
      {
        id: 'scielo',
        label: 'SciELO',
        value: 4,
        percentage: 13,
      },
      {
        id: 'latindex',
        label: 'Latindex',
        value: 2,
        percentage: 6,
      },
    ],
    publications: [
      {
        id: 'pub-1',
        title: 'Modelo predictivo para gestión académica universitaria',
        authors: 'Dra. Elena Vizcarra, Mg. Carlos Aranda',
        journal: 'Revista de Ingeniería y Sistemas',
        group: 'DATASCI',
        indexation: 'Scopus',
        status: 'publicada',
        year: 2026,
        updatedAt: 'Actualizado hoy',
      },
      {
        id: 'pub-2',
        title: 'Seguridad aplicada a sistemas de investigación institucional',
        authors: 'Dr. Ricardo Palma, Ing. Ana Torres',
        journal: 'IEEE Latin America Transactions',
        group: 'RESEGTI',
        indexation: 'IEEE',
        status: 'revision',
        year: 2026,
        updatedAt: 'Hace 1 día',
      },
      {
        id: 'pub-3',
        title: 'Arquitectura de software para procesos académicos',
        authors: 'Mg. Luis Cárdenas',
        journal: 'Revista Científica FIIS',
        group: 'GINSOFT',
        indexation: 'SciELO',
        status: 'publicada',
        year: 2025,
        updatedAt: 'Hace 3 días',
      },
      {
        id: 'pub-4',
        title: 'Automatización de reportes en plataformas universitarias',
        authors: 'Dra. Mariana Salazar',
        journal: 'Cuadernos de Investigación Tecnológica',
        group: 'SISTEMAS',
        indexation: 'Latindex',
        status: 'borrador',
        year: 2026,
        updatedAt: 'En preparación',
      },
    ],
    summary: [
      'La mayor producción científica se concentra en publicaciones indexadas en Scopus.',
      'Los grupos DATASCI y GINSOFT presentan mayor actividad investigativa registrada.',
      'Las publicaciones en revisión requieren seguimiento editorial para evitar retrasos.',
    ],
  };
}

export async function getFinancingData(): Promise<FinancingData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'available-budget',
        title: 'Presupuesto disponible',
        value: 'S/ 185K',
        detail: 'para nuevas convocatorias',
        tone: 'primary',
      },
      {
        id: 'assigned-budget',
        title: 'Presupuesto asignado',
        value: 'S/ 420K',
        detail: 'distribuido en proyectos vigentes',
        tone: 'primary',
      },
      {
        id: 'pending-review',
        title: 'Solicitudes en evaluación',
        value: '09',
        detail: 'pendientes de validación presupuestal',
        tone: 'danger',
      },
      {
        id: 'active-calls',
        title: 'Convocatorias activas',
        value: '03',
        detail: 'fondos concursables abiertos',
        tone: 'primary',
      },
    ],
    sources: [
      {
        id: 'internal',
        name: 'Fondo interno FIIS',
        amount: 'S/ 210K',
        description: 'Financiamiento institucional para investigación docente.',
        percentage: 42,
      },
      {
        id: 'university',
        name: 'Fondo universitario',
        amount: 'S/ 160K',
        description: 'Recursos asignados por gestión central universitaria.',
        percentage: 32,
      },
      {
        id: 'external',
        name: 'Fondos externos',
        amount: 'S/ 90K',
        description: 'Convenios, alianzas y programas externos.',
        percentage: 18,
      },
      {
        id: 'seed',
        name: 'Capital semilla',
        amount: 'S/ 40K',
        description: 'Apoyo inicial para propuestas emergentes.',
        percentage: 8,
      },
    ],
    calls: [
      {
        id: 'fc-1',
        title: 'Fondo Concursable de Investigación 2026',
        code: 'FC-FIIS-2026-01',
        budget: 'S/ 120K',
        applicants: 18,
        status: 'abierta',
        deadline: 'Cierre: 30 Jun 2026',
      },
      {
        id: 'fc-2',
        title: 'Programa de Innovación Tecnológica',
        code: 'PIT-FIIS-2026-02',
        budget: 'S/ 95K',
        applicants: 11,
        status: 'evaluacion',
        deadline: 'Evaluación técnica',
      },
      {
        id: 'fc-3',
        title: 'Apoyo a Publicaciones Indexadas',
        code: 'API-FIIS-2026-03',
        budget: 'S/ 45K',
        applicants: 7,
        status: 'abierta',
        deadline: 'Cierre: 15 Jul 2026',
      },
      {
        id: 'fc-4',
        title: 'Fondo de Equipamiento para Laboratorios',
        code: 'FEL-FIIS-2026-04',
        budget: 'S/ 160K',
        applicants: 6,
        status: 'cerrada',
        deadline: 'Convocatoria cerrada',
      },
    ],
    summary: [
      'El fondo interno FIIS concentra la mayor parte del presupuesto disponible para investigación.',
      'Las convocatorias abiertas mantienen alta participación de grupos de investigación.',
      'Las solicitudes en evaluación requieren validación financiera antes de pasar a aprobación final.',
    ],
  };
}

export async function getRankingData(): Promise<RankingData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'top-score',
        title: 'Puntaje más alto',
        value: '94',
        detail: 'investigador destacado del periodo',
        tone: 'primary',
      },
      {
        id: 'active-researchers',
        title: 'Investigadores activos',
        value: '36',
        detail: 'con producción registrada',
        tone: 'primary',
      },
      {
        id: 'groups-ranked',
        title: 'Grupos evaluados',
        value: '08',
        detail: 'ranking institucional actualizado',
        tone: 'primary',
      },
      {
        id: 'follow-up',
        title: 'En seguimiento',
        value: '05',
        detail: 'requieren mayor actividad investigativa',
        tone: 'danger',
      },
    ],
    researchers: [
      {
        id: 'res-1',
        position: 1,
        name: 'Dra. Elena Vizcarra',
        group: 'DATASCI',
        score: 94,
        projects: 5,
        publications: 7,
        status: 'destacado',
      },
      {
        id: 'res-2',
        position: 2,
        name: 'Dr. Ricardo Palma',
        group: 'RESEGTI',
        score: 89,
        projects: 4,
        publications: 6,
        status: 'destacado',
      },
      {
        id: 'res-3',
        position: 3,
        name: 'Mg. Carlos Aranda',
        group: 'GINSOFT',
        score: 84,
        projects: 4,
        publications: 5,
        status: 'activo',
      },
      {
        id: 'res-4',
        position: 4,
        name: 'Dra. Mariana Salazar',
        group: 'SISTEMAS',
        score: 78,
        projects: 3,
        publications: 4,
        status: 'activo',
      },
      {
        id: 'res-5',
        position: 5,
        name: 'Ing. Ana Torres',
        group: 'RESEGTI',
        score: 71,
        projects: 2,
        publications: 3,
        status: 'seguimiento',
      },
    ],
    groups: [
      {
        id: 'grp-1',
        position: 1,
        name: 'DATASCI',
        score: 91,
        projects: 18,
        publications: 14,
        participation: 86,
      },
      {
        id: 'grp-2',
        position: 2,
        name: 'GINSOFT',
        score: 87,
        projects: 15,
        publications: 12,
        participation: 82,
      },
      {
        id: 'grp-3',
        position: 3,
        name: 'RESEGTI',
        score: 81,
        projects: 12,
        publications: 10,
        participation: 76,
      },
      {
        id: 'grp-4',
        position: 4,
        name: 'SISTEMAS',
        score: 73,
        projects: 9,
        publications: 6,
        participation: 64,
      },
    ],
    criteria: [
      {
        id: 'projects',
        title: 'Proyectos registrados',
        description: 'Cantidad y estado de proyectos postulados, aprobados y en ejecución.',
        weight: '35%',
      },
      {
        id: 'publications',
        title: 'Producción científica',
        description: 'Publicaciones indexadas, artículos en revisión y producción reciente.',
        weight: '30%',
      },
      {
        id: 'procedures',
        title: 'Cumplimiento administrativo',
        description: 'Entrega de informes, trazabilidad y regularidad documental.',
        weight: '20%',
      },
      {
        id: 'impact',
        title: 'Impacto institucional',
        description: 'Participación en convocatorias, colaboración y aporte estratégico.',
        weight: '15%',
      },
    ],
  };
}

export async function getResearchersData(): Promise<ResearchersData> {
  return {
    period: 'Junio 2026',
    metrics: [
      {
        id: 'active-researchers',
        title: 'Investigadores activos',
        value: '36',
        detail: 'con participación vigente',
        tone: 'primary',
      },
      {
        id: 'featured-researchers',
        title: 'Investigadores destacados',
        value: '08',
        detail: 'alta producción institucional',
        tone: 'primary',
      },
      {
        id: 'follow-up',
        title: 'En seguimiento',
        value: '05',
        detail: 'requieren actualización de actividad',
        tone: 'danger',
      },
      {
        id: 'groups',
        title: 'Grupos asociados',
        value: '08',
        detail: 'grupos de investigación FIIS',
        tone: 'primary',
      },
    ],
    distribution: [
      {
        id: 'datasci',
        group: 'DATASCI',
        total: 10,
        percentage: 28,
      },
      {
        id: 'ginsoft',
        group: 'GINSOFT',
        total: 9,
        percentage: 25,
      },
      {
        id: 'resegt',
        group: 'RESEGTI',
        total: 8,
        percentage: 22,
      },
      {
        id: 'sistemas',
        group: 'SISTEMAS',
        total: 5,
        percentage: 14,
      },
      {
        id: 'otros',
        group: 'Otros',
        total: 4,
        percentage: 11,
      },
    ],
    researchers: [
      {
        id: 'inv-1',
        name: 'Dra. Elena Vizcarra',
        role: 'Docente investigadora',
        group: 'DATASCI',
        email: 'elena.vizcarra@fiis.edu.pe',
        projects: 5,
        publications: 7,
        score: 94,
        status: 'destacado',
      },
      {
        id: 'inv-2',
        name: 'Dr. Ricardo Palma',
        role: 'Coordinador de investigación',
        group: 'RESEGTI',
        email: 'ricardo.palma@fiis.edu.pe',
        projects: 4,
        publications: 6,
        score: 89,
        status: 'destacado',
      },
      {
        id: 'inv-3',
        name: 'Mg. Carlos Aranda',
        role: 'Docente investigador',
        group: 'GINSOFT',
        email: 'carlos.aranda@fiis.edu.pe',
        projects: 4,
        publications: 5,
        score: 84,
        status: 'activo',
      },
      {
        id: 'inv-4',
        name: 'Dra. Mariana Salazar',
        role: 'Investigadora asociada',
        group: 'SISTEMAS',
        email: 'mariana.salazar@fiis.edu.pe',
        projects: 3,
        publications: 4,
        score: 78,
        status: 'activo',
      },
      {
        id: 'inv-5',
        name: 'Ing. Ana Torres',
        role: 'Investigadora junior',
        group: 'RESEGTI',
        email: 'ana.torres@fiis.edu.pe',
        projects: 2,
        publications: 3,
        score: 71,
        status: 'seguimiento',
      },
    ],
    summary: [
      'La mayor concentración de investigadores activos se encuentra en los grupos DATASCI y GINSOFT.',
      'Los investigadores destacados presentan alta participación en proyectos y publicaciones indexadas.',
      'Los investigadores en seguimiento requieren actualización de producción académica y participación en convocatorias.',
    ],
  };
}